# syntax=docker/dockerfile:1.7

FROM prefecthq/prefect:3.8.3-python3.11

ENV PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_ROOT_USER_ACTION=ignore

RUN --mount=type=cache,target=/root/.cache/pip,sharing=locked \
    python -m pip install "prefect[docker]==3.8.3"
