import type { ModulePresentation, ModuleType } from '../types';

export const MODULE_CATEGORIES = ['Source', 'Logic', 'Transform', 'Output'] as const;

/** UI-only metadata. Labels, descriptions, and I/O contracts come from the backend. */
export const MODULE_PRESENTATION: Partial<Record<ModuleType, ModulePresentation>> = {
  query_input: { icon: 'MessageSquare', color: '#107c41' },
  direct_query_decomposer: { icon: 'ArrowRight', color: '#475569' },
  decomposer: { icon: 'GitBranch', color: '#7c3aed' },
  thesaurus_decomposer: { icon: 'Languages', color: '#7c3aed' },
  adaptive_query_decomposer: { icon: 'GitBranch', color: '#6d28d9' },
  template_query_decomposer: { icon: 'FileCode', color: '#4f46e5' },
  embedder: { icon: 'Cpu', color: '#0891b2' },
  batch_query_embedder: { icon: 'Cpu', color: '#0891b2' },
  cell_text_embedder: { icon: 'Binary', color: '#0f766e' },
  pgvector_index_writer: { icon: 'Database', color: '#0f766e' },
  pgvector_collection_loader: { icon: 'Database', color: '#0f766e' },
  multi_company_collection_loader: { icon: 'Building2', color: '#0f766e' },
  pgvector_retriever: { icon: 'Search', color: '#0f766e' },
  semantic_scoped_pgvector_retriever: { icon: 'SearchCheck', color: '#0f766e' },
  postgres_native_keyword_retriever: { icon: 'ListFilter', color: '#2563eb' },
  semantic_query_matcher: { icon: 'Route', color: '#7c3aed' },
  llm_query_router: { icon: 'Bot', color: '#c026d3' },
  semantic_scoped_dense_retriever: { icon: 'SearchCheck', color: '#0f766e' },
  rrf_fusion: { icon: 'Merge', color: '#059669' },
  adaptive_rrf_fusion: { icon: 'Merge', color: '#059669' },
  context: { icon: 'Maximize2', color: '#d97706' },
  pg_context_expander: { icon: 'Maximize2', color: '#d97706' },
  timeseries_context_expander: { icon: 'TrendingUp', color: '#d97706' },
  reader: { icon: 'Sparkles', color: '#e11d48' },
  financial_formula_calculator: { icon: 'Calculator', color: '#e11d48' },
  answer_refiner: { icon: 'Sparkles', color: '#059669' },
  processed_file_selector: { icon: 'FileSpreadsheet', color: '#107c41' },
  bfs_llm_structure_detector: { icon: 'Network', color: '#0f766e' },
  luna_vlm_structure_detector: { icon: 'CloudCog', color: '#4338ca' },
  company_entity_extractor: { icon: 'Building2', color: '#7c3aed' },
  docling_table_detector: { icon: 'ScanSearch', color: '#0891b2' },
  openpyxl_region_detector: { icon: 'TableProperties', color: '#d97706' },
  cell_text_serializer: { icon: 'Rows3', color: '#7c3aed' },
  exhaustive_cell_text_serializer: { icon: 'Shuffle', color: '#9333ea' },
  sheet_metadata_persistence: { icon: 'TableProperties', color: '#d97706' },
  index_company_persistence: { icon: 'Building2', color: '#7c3aed' },
  dataframe_source: { icon: 'TableProperties', color: '#2563eb' },
  image_tile_source: { icon: 'Layers', color: '#7c3aed' },
  qa_example_loader: { icon: 'MessageSquare', color: '#d97706' },
};
